language: node_js
node_js:
  - '8'
sudo: true
cache:
  yarn: true
  directories:
    - "node_modules"
install:
  - yarn global add @vue/cli
  - yarn install
  - yarn build
script: true
deploy:
  provider: pages
  local-dir: ./dist
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  target-branch: master
  on:
    branch: source
notifications:
  email:
    - atsunaakiya@outlook.com
    - 2357321824@qq.com